<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-5V96AT9" name="Test2" tests="6" failures="1" timestamp="25 Nov 2019 07:14:59 GMT" time="26.231" errors="0">
  <testcase name="Login" time="1.067" classname="com.AS.testcases.BankManagerLogin"/>
  <testcase name="addNewCustomer" time="2.812" classname="com.AS.testcases.AddCustomer"/>
  <testcase name="addNewCustomer" time="1.51" classname="com.AS.testcases.AddCustomer"/>
  <testcase name="addNewCustomer" time="6.212" classname="com.AS.testcases.AddCustomer"/>
  <testcase name="addNewCustomer" time="1.468" classname="com.AS.testcases.AddCustomer"/>
  <testcase name="openAccount" time="2.836" classname="com.AS.testcases.OpenAccount">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.AS.testcases.OpenAccount.openAccount(OpenAccount.java:32)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- openAccount -->
</testsuite> <!-- Test2 -->
